Acme\UserBundle\Entity\UsersRole:
    type: entity
    table: users_role
    indexes:
        user:
            columns:
                - user
                - role
        role:
            columns:
                - role
        IDX_98E0C4648D93D649:
            columns:
                - user
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        description:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
    manyToOne:
        role:
            targetEntity: Role
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                role:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: AutenUsers
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
